'use strict';

// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_UNAUTHORIZED = 'LOGIN_UNAUTHORIZED';
export const SWITCH_KEEP_SESSION_ID= 'SWITCH_KEEP_SESSION_ID';

// Locale actions
export const LOCALE_LIST_REQUEST = 'LOCALE_LIST_REQUEST';
export const LOCALE_LIST_SUCCESS = 'LOCALE_LIST_SUCCESS';
export const LOCALE_CHANGE = 'LOCALE_CHANGE';

// Accounts actions
export const ACCOUNT_INFO_REQUEST     = 'ACCOUNT_INFO_REQUEST';
export const ACCOUNT_INFO_RECEIVED    = 'ACCOUNT_INFO_RECEIVED';
export const ACCOUNT_INFO_NOT_FOUND   = 'ACCOUNT_INFO_NOT_FOUND';
export const ACCOUNT_INFO_SAVE        = 'ACCOUNT_INFO_SAVE';
export const ACCOUNT_INFO_SAVE_DONE   = 'ACCOUNT_INFO_SAVE_DONE';
export const ACCOUNT_INFO_UPDATE      = 'ACCOUNT_INFO_UPDATE';
export const ACCOUNT_INFO_UPDATE_DONE = 'ACCOUNT_INFO_UPDATE_DONE';
export const ACCOUNT_DELETE           = 'ACCOUNT_DELETE';
export const ACCOUNT_DELETE_SUCCESS   = 'ACCOUNT_DELETE';

export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST';
export const ACCOUNT_LIST_RECEIVED = 'ACCOUNT_LIST_RECEIVED';
export const ACCOUNT_LIST_SORT = 'ACCOUNT_LIST_SORT';
export const ACCOUNT_LIST_SEARCH = 'ACCOUNT_LIST_SEARCH';
export const ACCOUNT_LIST_MORE = 'ACCOUNT_LIST_MORE';
export const ACCOUNT_LIST_MORE_REQUEST = 'ACCOUNT_LIST_MORE_REQUEST';
export const ACCOUNT_LIST_CHANGE_SELECTION = 'ACCOUNT_LIST_CHANGE_SELECTION';
export const ACCOUNT_LIST_UPDATE_SEARCH_QUERY = 'ACCOUNT_LIST_UPDATE_SEARCH_QUERY';

// Leads actions
export const LEADS_LIST_RECEIVED = 'LEADS_LIST_RECEIVED';

export const GLOBAL_PARAMS_CATEGORY_REQUEST = 'GLOBAL_PARAMS_CATEGORY_REQUEST';
export const GLOBAL_PARAMS_TYPE_REQUEST = 'GLOBAL_PARAMS_TYPE_REQUEST';
export const GLOBAL_PARAMS_RECEIVED = 'GLOBAL_PARAMS_RECEIVED';

// Page Controls
export const PAGE_CONTROLS_REQUEST = 'PAGE_CONTROLS_REQUEST';
export const PAGE_CONTROLS_SUCCESS = 'PAGE_CONTROLS_SUCCESS';

export const PAGE_OVERVIEW_CONTROLS_SUCCESS = 'PAGE_OVERVIEW_CONTROLS_SUCCESS';

// User Action
export const USER_LIST_REQUEST        = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS        = 'USER_LIST_SUCCESS';

// Select options actions
export const SELECT_OPTIONS_REQUEST   = 'SELECT_OPTIONS_REQUEST';
export const SELECT_OPTIONS_RECEIVED  = 'SELECT_OPTIONS_RECEIVED';

export const SELECT_OPTIONS_UPDATE_SUCCESS  = 'SELECT_OPTIONS_UPDATE_SUCCESS';

export const SELECT_OPTION_REQUEST   = 'SELECT_OPTION_REQUEST';
export const SELECT_OPTION_RECEIVED  = 'SELECT_OPTION_RECEIVED';

export const SELECT_OPTION_LIST_UPDATE  = 'SELECT_OPTION_LIST_UPDATE';

// UI State
export const SWITCH_SIDEBAR = 'SWITCH_SIDEBAR';

// CRM Params actions
export const CRM_PARAMS_REQUEST         = 'CRM_PARAMS_REQUEST';
export const CRM_PARAMS_RECEIVED        = 'CRM_PARAMS_RECEIVED';

export const PAGE_LOGIN_CONTROLS_SUCCESS                = 'PAGE_LOGIN_CONTROLS_SUCCESS';
export const PAGE_ACCOUNTS_OVERVIEW_CONTROLS_SUCCESS    = 'PAGE_ACCOUNTS_OVERVIEW_CONTROLS_SUCCESS';
export const PAGE_ACCOUNT_DETAILS_CONTROLS_SUCCESS      = 'PAGE_ACCOUNT_DETAILS_CONTROLS_SUCCESS';
export const PAGE_LEADS_OVERVIEW_CONTROLS_SUCCESS       = 'PAGE_LEADS_OVERVIEW_CONTROLS_SUCCESS';
